development:
  adapter: postgresql
  encoding: unicode
  database: covidhub_development
  pool: 5
  username: covidhub
  password: 12345678
  host: localhost
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: covidhub_test
  pool: 5
  username: covidhub
  password: 12345678
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: covidhub
  pool: 5
  username: covidhub
  password: 12345678
  host: localhost
  port: 5433
