development:
  adapter: postgresql
  encoding: unicode
  database: simplehub_development
  pool: 5
  username: simplehub
  password: 12345678
  host: localhost
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: simplehub_test
  pool: 5
  username: simplehub
  password: 12345678
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: simplehub_production